CREATE TABLE EMPLEADOS(
    Id_empleado BIGINT PRIMARY KEY IDENTITY(1,1), 
    Nombre NVARCHAR(250) NOT NULL,
    Apellido NVARCHAR(250) NOT NULL,
    Direccion NVARCHAR(250) NOT NULL,
    Localidad NVARCHAR(250) NOT NULL,
    Provincia NVARCHAR(250) NOT NULL,
    FechaIngresoSistema DATE DEFAULT GETDATE(),
    Activo BIT NOT NULL
)

GO

CREATE TABLE PROFESORES(
    Id_profesor BIGINT PRIMARY KEY IDENTITY(1,1), 
    Nombre NVARCHAR(250) NOT NULL,
    Apellido NVARCHAR(250) NOT NULL,
    Direccion NVARCHAR(250) NOT NULL,
    Curso NVARCHAR(100) NOT NULL,
    Materia NVARCHAR(100) NOT NULL
    FechaIngresoSistema DATE DEFAULT GETDATE(), 
    Activo BIT NOT NULL
)
